[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Packages.gd", "nginx"]

[phases.install]
cmds = ["composer install --no-interaction --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache",
    "chmod -R 775 storage bootstrap/cache"
]

[variables]
NIXPACKS_PHP_ROOT = "."
NIXPACKS_PHP_FALLBACK_PATH = "/index.php"
NIXPACKS_NO_NODEJS = "1"
RAILWAY_BUILDER_TYPE = "nixpacks"
