[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nginx"]

[phases.install]
cmds = ["composer install --no-interaction --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "apachectl -D FOREGROUND" # Попробуем другой способ запуска или вернемся к переменным

[variables]
NIXPACKS_PHP_ROOT = "."
NIXPACKS_PHP_FALLBACK_PATH = "/index.php"
